apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      automountServiceAccountToken: false
      containers:
        - name: spring
          image: gomgoguma/kube:v0.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
